### PR TITLE
Added 'progress' event support for sftp file writing.

### PR DESCRIPTION
**Pull request by 0xorial**
Connected to my pull request here: https://github.com/mscdex/ssh2-streams/pull/12

### CODE REVIEW

**Comment by zensh** [comment]
As @mscdex 's opinion, it dose not make sense.

**Comment by 0xorial** [comment]
Is there a reason why gulp-ssh does not use fast{get/put} from ssh2?

**Comment by zensh** [comment]
This plugin should refactor with [ssh2-streams](https://github.com/mscdex/ssh2-streams), I will do it this weekend.

**Comment by mscdex** [comment]
Just to clear up any confusion, `ssh2-streams` is not something that most users will want to use directly, as it operates at a very low level. Using `sftp.fastGet()`/`sftp.fastPut()` from the `ssh2` module is possible without using `ssh2-streams` explicitly.

**Comment by zensh** [comment]
@mscdex Thank you for your suggestion.

**Pull request closed without merging**
