### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by mojavelinux**
- add test fixtures
- add tests for all operations (exec, shell, sftp, dest)
- add chai-fs for testing for the existence of files and directories
- add fs-extra for test cleanup
- rename gulp test task to samples

### CODE REVIEW

**Comment by mojavelinux** [comment]
Uh oh. sftp subsystem isn't working in Travis CI. Investigating...

**Comment by mojavelinux** [comment]
Travis is happy now!

**Comment by mojavelinux** [comment]
Should we test against Node 4?

**Comment by zensh** [comment]
Thank you.
Node 4 is unnecessary.

**Comment by mojavelinux** [comment]
:tada:

**Comment by mojavelinux** [comment]
Now that I have the test suite set up, I have a list of tests I still want to add. I'll keep 'em coming.

**Pull request merged**
